### ISSUE TITLE
Error code (183)

### ISSUE THREAD

**Issue by Vega-ss** [networkMe/missinghud2#24] opened 2015-11-07 00:20 UTC
---------------------------

---------------------------
Error occurred.
---------------------------
boost::interprocesscommunication error occured. Check MHUD2.log for details.
---------------------------
OK   
---------------------------

![hud issue](https://cloud.githubusercontent.com/assets/15697825/11011908/af05c1be-84f5-11e5-84c0-78684050b88f.png)
![hud issue](https://cloud.githubusercontent.com/assets/15697825/11011924/00b5764e-84f6-11e5-8856-d306189d3390.png)

**Comment by Vega-ss** [comment] 2015-11-07 04:17
How to fix the error?

**Comment by networkMe** [comment] 2015-11-07 12:04
This issue is a duplicate of issue #18

**Closed by networkMe** 2015-11-07 12:04 UTC
